### ISSUE TITLE
Windows Buildkite agents are taking new jobs before the VM has rebooted

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/sandboxed-buildkite-agent#42]

**Comment by DilumAluthge** [comment]
This often manifests itself with the following error message:

> "Secret private key path 'C:\secrets/agent.key' is not a valid private RSA key!"

**Comment by staticfloat** [comment]
Thanks to the debugging code added in, we can see in this example that the previous run was canceled by a SIGINT, presumably sent because the entire job was canceled due to a new commit being pushed before the old commit was done testing:

Old run: https://buildkite.com/julialang/julia-master/builds/20727#0186216b-d26a-4bde-b924-469346201a0b/4392-4408
New run: https://buildkite.com/julialang/julia-master/builds/20728#01862174-1b9b-4a4a-8aa9-a548b4eb7635/6-23

This _shouldn't_ cause a problem, but clearly we do have a problem, so let's trace through and see if we can find any issues with our reboot functionality:

* First, buildkite itself should exit after running.  Given that we have [new PIDs](https://buildkite.com/julialang/julia-master/builds/20728#01862174-1b9b-4a4a-8aa9-a548b4eb7635/6-29) for the buildkite-agent processes, this seems to be likely working as intended.
* Next, `nssm` [should be invoking `shutdown`](https://github.com/JuliaCI/sandboxed-buildkite-agent/blob/30d475ded932208c2afcfc1034410fbf2b716a54/windows-kvm/buildkite-worker/setup_scripts/0-02-install-buildkite-agent.ps1#L14) immediately after the `buildkite-agent` process exits.  It's unclear if this is happening or not.
* Once the VM shuts down, the state of the VM should be reset.  Looking through the VM logs, it is not restarting.

So the smoking gun points to, unsurprisingly, the NSSM script that should be invoking shutdown, but it's failing for some reason.

**Comment by Keno** [comment]
> * Next, `nssm` [should be invoking `shutdown`](https://github.com/JuliaCI/sandboxed-buildkite-agent/blob/30d475ded932208c2afcfc1034410fbf2b716a54/windows-kvm/buildkite-worker/setup_scripts/0-02-install-buildkite-agent.ps1#L14) immediately after the `buildkite-agent` process exits.  It's unclear if this is happening or not.

I'm always nervous about shell quoting, particularly on Windows. Are we sure that this ends up getting parsed appropriately by `cmd` and not appended as garbage to the end of the buildkite invocation or to some internal command line inside nssm?

**Comment by staticfloat** [comment]
I logged into a machine running a job, and used a powershell script to tail the windows event log for `nssm` and for `User32`, this is what I saw:

```
   ProviderName: nssm

TimeCreated                      Id LevelDisplayName Message
-----------                      -- ---------------- -------
7/26/2024 5:52:02 PM           1040 Information      Service buildkite-agent received START control, which will be handled.
7/26/2024 5:52:04 PM           1008 Information      Started C:\Windows\System32\cmd.exe /C C:\buildkite-agent\bin\buildkite-agent.exe start & shutdown /s /t 0 /f /d p:4:1 for service buildkite-agent in C:\W... 
7/26/2024 5:52:17 PM           1040 Information      Service buildkite-agent received SHUTDOWN control, which will be handled.
7/26/2024 5:52:17 PM           1011 Information      Killing process C:\Windows\System32\cmd.exe because service buildkite-agent is stopping.
7/26/2024 5:52:31 PM           1040 Information      Service buildkite-agent received START control, which will be handled.
7/26/2024 5:52:32 PM           1008 Information      Started C:\Windows\System32\cmd.exe /C C:\buildkite-agent\bin\buildkite-agent.exe start & shutdown /s /t 0 /f /d p:4:1 for service buildkite-agent in C:\W... 
7/26/2024 5:52:02 PM           1040 Information      Service buildkite-agent received START control, which will be handled.                                                                                       
7/26/2024 5:52:04 PM           1008 Information      Started C:\Windows\System32\cmd.exe /C C:\buildkite-agent\bin\buildkite-agent.exe start & shutdown /s /t 0 /f /d p:4:1 for service buildkite-agent in C:\W... 
7/26/2024 5:52:17 PM           1040 Information      Service buildkite-agent received SHUTDOWN control, which will be handled.
7/26/2024 5:52:17 PM           1011 Information      Killing process C:\Windows\System32\cmd.exe because service buildkite-agent is stopping.
7/26/2024 5:52:31 PM           1040 Information      Service buildkite-agent received START control, which will be handled.
7/26/2024 5:52:32 PM           1008 Information      Started C:\Windows\System32\cmd.exe /C C:\buildkite-agent\bin\buildkite-agent.exe start & shutdown /s /t 0 /f /d p:4:1 for service buildkite-agent in C:\W...
7/26/2024 6:21:31 PM           1013 Information      Program C:\Windows\System32\cmd.exe for service buildkite-agent exited with return code 0.
7/26/2024 6:21:31 PM           1023 Information      Killing process tree of process 4048 for service buildkite-agent with exit code 0
7/26/2024 6:21:31 PM           1027 Information      Killing PID 4048 in process tree of PID 4048 because service buildkite-agent is stopping.
7/26/2024 6:21:31 PM           1016 Information      Service buildkite-agent action for exit code 0 is Exit. Exiting.
7/26/2024 6:21:31 PM           1012 Information      Requested stop of service buildkite-agent.  No action is required as program C:\Windows\System32\cmd.exe is not running.
```

```
   ProviderName: User32

TimeCreated                      Id LevelDisplayName Message                                                                                                                                                      
-----------                      -- ---------------- -------                                                                                                                                                      
6/26/2024 1:37:33 AM           1074 Information      The process C:\Windows\system32\winlogon.exe (MINWINPC) has initiated the restart of computer WIN-HKTBISMGI26 on behalf of user NT AUTHORITY\SYSTEM for th...
6/25/2024 6:46:41 PM           1074 Information      The process C:\Windows\system32\wbem\wmiprvse.exe (WINBASE) has initiated the restart of computer WINBASE on behalf of user WINBASE\julia for the followin...
6/25/2024 7:04:29 PM           1074 Information      The process C:\Windows\system32\wbem\wmiprvse.exe (WINBASE) has initiated the restart of computer WINBASE on behalf of user WINBASE\julia for the followin...
6/25/2024 7:17:11 PM           1074 Information      The process wininit.exe (WINBASE) has initiated the power off of computer WINBASE on behalf of user WINBASE\Administrator for the following reason: Applic...
6/25/2024 7:24:09 PM           1074 Information      The process wininit.exe (WINBASE) has initiated the power off of computer WINBASE on behalf of user WINBASE\Administrator for the following reason: Applic...
7/26/2024 5:52:08 PM           1074 Information      The process C:\Windows\system32\winlogon.exe (WIN2K22-AMDCI6-) has initiated the restart of computer WIN2K22-AMDCI6- on behalf of user NT AUTHORITY\SYSTEM...
6/26/2024 1:37:33 AM           1074 Information      The process C:\Windows\system32\winlogon.exe (MINWINPC) has initiated the restart of computer WIN-HKTBISMGI26 on behalf of user NT AUTHORITY\SYSTEM for th...
6/25/2024 6:46:41 PM           1074 Information      The process C:\Windows\system32\wbem\wmiprvse.exe (WINBASE) has initiated the restart of computer WINBASE on behalf of user WINBASE\julia for the followin...
6/25/2024 7:04:29 PM           1074 Information      The process C:\Windows\system32\wbem\wmiprvse.exe (WINBASE) has initiated the restart of computer WINBASE on behalf of user WINBASE\julia for the followin...
6/25/2024 7:17:11 PM           1074 Information      The process wininit.exe (WINBASE) has initiated the power off of computer WINBASE on behalf of user WINBASE\Administrator for the following reason: Applic...
6/25/2024 7:24:09 PM           1074 Information      The process wininit.exe (WINBASE) has initiated the power off of computer WINBASE on behalf of user WINBASE\Administrator for the following reason: Applic...
7/26/2024 5:52:08 PM           1074 Information      The process C:\Windows\system32\winlogon.exe (WIN2K22-AMDCI6-) has initiated the restart of computer WIN2K22-AMDCI6- on behalf of user NT AUTHORITY\SYSTEM...
7/26/2024 6:21:31 PM           1074 Information      The process C:\Windows\System32\shutdown.exe (WIN2K22-AMDCI6-) has initiated the shutdown of computer WIN2K22-AMDCI6- on behalf of user WIN2K22-AMDCI6-\ju...
```

So it looks to me like it is correctly invoking the `shutdown` command.  In any case, if it weren't, our bots wouldn't work at all, rather than not working sporadically.

**Comment by staticfloat** [comment]
I wonder if `shutdown` can ever fail?  Is that possible?

**Comment by Keno** [comment]
Those are all the success case though. Do we have any logs for the failure case?

**Comment by staticfloat** [comment]
No, I have to login and instrument the VM beforehand, as all state is lost after each job finishes.

**Comment by Keno** [comment]
Can we dump the logs in one of the early scripts if `C:\secrets/agent.key` is missing, which is one of the indicators of this failure?

**Comment by IanButterworth** [comment]
I've tried to put that suggestion together here https://github.com/JuliaCI/cryptic-buildkite-plugin/pull/35

**Comment by IanButterworth** [comment]
We caught it and got logs here https://buildkite.com/julialang/julia-buildkite/builds/2037#01960083-fe60-4388-ade5-d77ac10f7cca/1-7

I don't think it tells us much, right? Could it be that we're killing the process that's orchestrating SHUTDOWN? Seems unlikely
```
  | > C:\buildkite-agent\hooks\environment
  | -> source C:\buildkite-agent\hooks/environment.d/100_gr_env.sh
  | -> source C:\buildkite-agent\hooks/environment.d/101_julia_num_cores.sh
  | -> source C:\buildkite-agent\hooks/environment.d/110_windows_cache_drive.sh
  | -> source C:\buildkite-agent\hooks/environment.d/999_cryptic_unlock.sh
  | Unable to open agent private key path 'C:\secrets/agent.key'!  Make sure your agent has this file deployed within it!
  | NOTE: This is a known bug where this agent is old, caused by the agent not restarting after a previous job.
  | see https://github.com/JuliaCI/sandboxed-buildkite-agent/issues/42
  | Showing debug information...
  |  
  | ProviderName: nssm
  |  
  |  
  | TimeCreated            Id LevelDisplayName Message
  | -----------            -- ---------------- -------
  | 4/4/2025 11:52:59 AM 1040 Information      Service buildkite-agent received START control, which will be handled.
  | 4/4/2025 11:53:01 AM 1008 Information      Started C:\Windows\System32\cmd.exe /C C:\buildkite-agent\bin\buildkite-a...
  | 4/4/2025 11:53:12 AM 1040 Information      Service buildkite-agent received SHUTDOWN control, which will be handled.
  | 4/4/2025 11:53:12 AM 1011 Information      Killing process C:\Windows\System32\cmd.exe because service buildkite-age...
  | 4/4/2025 11:53:24 AM 1040 Information      Service buildkite-agent received START control, which will be handled.
  | 4/4/2025 11:53:25 AM 1008 Information      Started C:\Windows\System32\cmd.exe /C C:\buildkite-agent\bin\buildkite-a...
  |  
  |  
  |  
  | ProviderName: User32
  |  
  | Get-WinEvent : No events were found that match the specified selection criteria.
  | At line:5 char:13
  | +             Get-WinEvent -LogName Application -FilterXPath "*[System[ ...
  | +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | + CategoryInfo          : ObjectNotFound: (:) [Get-WinEvent], Exception
  | + FullyQualifiedErrorId : NoMatchingEventsFound,Microsoft.PowerShell.Commands.GetWinEventCommand
  |  
  | 🚨 Error: Error setting up job executor: The global environment hook exited with status 1

```

**Comment by staticfloat** [comment]
Okay, I think I finally understand what's going on here.

Our [service executable is the following `cmd` line](https://github.com/JuliaCI/sandboxed-buildkite-agent/blob/main/windows-kvm/buildkite-worker/setup_scripts/0-02-install-buildkite-agent.ps1#L14
):
```
"C:\Windows\System32\cmd.exe" "/C C:\buildkite-agent\bin\buildkite-agent.exe start & shutdown /s /t 0 /f /d p:4:1"
```

Which causes a shutdown event to begin when the `buildkite-agent.exe` exits.  However, [`nssm` is actually set up to detect shutdown events](https://github.com/kirillkovalenko/nssm/blob/9b377191952f38a47b27d8d2a132e1e773967401/service.cpp#L1868) (Also see [relevant MSDN docs](https://learn.microsoft.com/en-us/windows/win32/api/winsvc/ns-winsvc-service_status)), and so kills our `cmd.exe` while it's attempting to run a system shutdown.  My theory here is that the sequence of events is:

1. `buildkite-agent.exe` finishes its job
2. `shutdown.exe` starts to run
3. `nssm` receives the shutdown event, kills the service
4. `nssm` then helpfully restarts the service after 10s, [as configured to here](https://github.com/JuliaCI/sandboxed-buildkite-agent/blob/a8845791aa20dc79dcaa39068b656056ca6d96e8/windows-kvm/buildkite-worker/setup_scripts/0-02-install-buildkite-agent.ps1#L19)
5. `buildkite-agent.exe` starts up again, but then receives a kill signal almost immediately because it just takes windows somewhere around 10s to shut itself down.

This issue is intermittent because there are lots of opportunities here for the issue to hide itself (taking less than 10s to shutdown, for instance).

Ideally, `nssm` wouldn't restart the service under any circumstances..... which I already tried to get it to do [on this line](https://github.com/JuliaCI/sandboxed-buildkite-agent/blob/a8845791aa20dc79dcaa39068b656056ca6d96e8/windows-kvm/buildkite-worker/setup_scripts/0-02-install-buildkite-agent.ps1#L18C28-L18C35).  Perhaps there's some issue with that.  I will try to test out some `nssm` options later this week to see if I can figure out what's wrong with this configuration.

**Comment by staticfloat** [comment]
I have pushed https://github.com/JuliaCI/sandboxed-buildkite-agent/pull/101 as a first attempt to change how this is done; I'm currently deploying that to the buildkite agents, we'll see if this has any effect.  It should at least change our debugging output a bit.

**Comment by vtjnash** [comment]
Still happening: https://buildkite.com/julialang/julia-master/builds/46712#01963b0b-c505-4092-b616-c22c50d4fabb. Note that previous job was canceled for no apparent reason though.

**Comment by giordano** [comment]
I think this got a lot worse over the last few weeks, see for example https://buildkite.com/julialang/julia-master/builds/46802#01965227-eb8d-4411-b719-38e104f66a2d

![Image](https://github.com/user-attachments/assets/44a87b89-d7f0-47d0-8e7c-5ddd29967b5d)

To make things worse, agents 3, 4, and 6 are just unable to start any job for some reason.
